### ISSUE TITLE
webrtc

### ISSUE THREAD

**Issue by qdwds** [forward-media/dove-into-webrtc#1]
买的您的webrtc书籍，因为是第一次接触，所有很多不懂。书上的代码好多东西都找不到对应的代码，就比如  34页  pc.addStrame(stream)   这个是什么呢？ 能整理一些对应的案例吗？我看了好多地方 东西都对不上，实在无从学习

**Comment by wistingcn** [comment]
书中所有代码都在这个地址里，而且都是按照章节划分的，很好找。

**Comment by loveyacper** [comment]
> 买的您的webrtc书籍，因为是第一次接触，所有很多不懂。书上的代码好多东西都找不到对应的代码，就比如 34页 pc.addStrame(stream) 这个是什么呢？ 能整理一些对应的案例吗？我看了好多地方 东西都对不上，实在无从学习

看了下电子版预览，完全是罗列api，这样也算是写书？？？

**Comment by loveyacper** [comment]
要点脸好吗？？？2021年了，还这么写书！！！？？？

**Comment by qdwds** [comment]
> > 买的您的webrtc书，因为是第一次接触，所有很多不懂。书上的代码好多东西都找到对应的代码，就放在34页pc.addStrame（stream）这个是什么呢？能整理一些对应的案例吗？我看了好多地方东西都对不上，实在无从学习
> 
> 看了下电子版预览，完全是罗列api，这样也算是写书？？？

我也是受害者，不要对着我喷 谢谢

**Comment by loveyacper** [comment]
> > > 买的您的webrtc书，因为是第一次接触，所有很多不懂。书上的代码好多东西都找到对应的代码，就放在34页pc.addStrame（stream）这个是什么呢？能整理一些对应的案例吗？我看了好多地方东西都对不上，实在无从学习
> > 
> > 
> > 看了下电子版预览，完全是罗列api，这样也算是写书？？？
> 
> 我也是受害者，不要对着我喷 谢谢

不好意思。这书你如果能看下去，也是佩服，哈哈；国人写书真的是一次次突破下限。
